version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: auraflux_postgres
    # restart: always
    volumes:
      - auraflux_data:/var/lib/postgresql/data/
    env_file:
      - ./docker-vars.env # Specify the path to the environment file to load
      - ./docker-vars.override.env
    ports:
      - "5432:5432"
    networks:
      - auraflux_network

  redis:
    image: redis:8.0.5-alpine3.21
    container_name: auraflux_redis
    # restart: always
    ports:
      - "6379:6379" # Expose Redis port (optional, but useful for debugging)
    networks:
      - auraflux_network

  nexus: &backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auraflux_nexus
    # restart: always
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./docker-vars.env
      - ./docker-vars.override.env
    networks:
      - auraflux_network

  worker:
    <<: *backend
    container_name: auraflux_worker
    env_file:
      - ./docker-vars.env
      - ./docker-vars.override.env
    ports: []
    volumes:
      - ./api:/api
    command: celery -A core.celery_app:celery_app worker -c 2 -l info
    networks:
      - auraflux_network

volumes:
  auraflux_data:

networks:
  auraflux_network:
    name: auraflux_network
    external: true
